# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 460c57a5aead6c0cf954372d8597056316b302ad91ff9fd8cb4ea4c9261101423f4d4df2952c465ebd7656cffb8c9c0be5128bcd090d6dd73ec2ab5948413018

test:
  secret_key_base: d8995de1ee876b7c567cb447ed5b642bbf43ddb93a9feb340d18cc4ac1174c0b21979d21554b09b13a1073b1014cbbdcff159bb369860d856792f4f2d69012e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
